name: Docker CI - Build & Push to GCP Artifact Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  PROJECT_ID: winppk-app01
  REGION: us-central1
  REPO: todorepo
  IMAGE_NAME: todoimg
  IMAGE_TAG: todotag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # REQUIRED for OIDC

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/259655456214/locations/global/workloadIdentityPools/github-actions-docker-cloudrun02/providers/github-actions
          service_account: github-sa-cloudrun@winppk-app01.iam.gserviceaccount.com

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Docker build
        run: |
          docker build -t todoimg:todotag .

      - name: Docker images (verify)
        run: |
          docker images

      - name: Docker tag
        run: |
          docker tag todoimg:todotag us-central1-docker.pkg.dev/winppk-app01/todorepo/todoimg:todotag

      - name: Docker push
        run: |
          docker push us-central1-docker.pkg.dev/winppk-app01/todorepo/todoimg:todotag
